laundry/urls.py
# reservations/urls.py
from django.urls import path
from .views import reserve_laundry, show_today, show_selected_day, ShowSelectedDayView
#from . views import show_calendar
app_name = 'laundry'

urlpatterns = [
    path('reserve/', reserve_laundry, name='reserve_laundry'),
    path('show_today/', show_today, name='show_today'),
    path('show_selected_day/', show_selected_day, name='show_selected_day'),
    # path('cal/', show_calendar, name='show_calendar'),
    # path('calendar/<int:year>/<int:month>/', show_calendar, name='show_calendar'),
    path('show_selected_dayy/', ShowSelectedDayView.as_view(), name='show_selected_dayy'),
]

myapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('laundry.urls')),

]

laundry/models.py
# main/models.py
from django.db import models
from django.contrib.auth.models import User

class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    

    def __str__(self):
        # Formatuj godziny za pomocą strftime, aby uzyskać tylko godziny (bez minut)
        start_time_str = self.start_time.strftime('%H:%M')
        end_time_str = self.end_time.strftime('%H:%M')

        return f"{self.user.username} - {self.date} {start_time_str}-{end_time_str}"

laundry/forms.py
# reservations/forms.py
# from django import forms
# from bootstrap_datepicker_plus.widgets import DatePickerInput
# from .models import Reservation

# class ReservationForm(forms.ModelForm):
#     class Meta:
#         model = Reservation
#         fields = ['date', 'start_time', 'end_time']
#         widgets = {
#             'date': DatePickerInput(format='%Y-%m-%d'),
#             'start_time': forms.TimeInput(attrs={'type': 'time'}),
#             'end_time': forms.TimeInput(attrs={'type': 'time'}),
#         }

# class DateForm(forms.Form):
#     date = forms.DateField(widget=DatePickerInput(format='%Y-%m-%d'))


from django import forms
from bootstrap_datepicker_plus.widgets import DatePickerInput
from .models import Reservation

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['date', 'start_time', 'end_time']
        widgets = {
            'date': DatePickerInput(options={'format': 'YYYY-MM-DD'}),
            'start_time': forms.TimeInput(attrs={'type': 'time'}),
            'end_time': forms.TimeInput(attrs={'type': 'time'}),
        }

class DateForm(forms.Form):
    date = forms.DateField(widget=DatePickerInput(options={'format': 'YYYY-MM-DD'}))


            

laundry/views.py
# reservations/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Reservation
from .forms import ReservationForm
from .forms import DateForm
from .utils import get_schedule_for_date
from datetime import datetime, timedelta

def reserve_laundry(request):
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            reservation = form.save(commit=False) # przy zapisywaniu formularza, aby uzyskać dostęp do utworzonego obiektu Reservation przed zapisaniem go do bazy danych. 
            reservation.user = request.user  # Przypisz aktualnego użytkownika
            reservation.save()
            messages.success(request, 'Rezerwacja pomyślnie dokonana.')
            return redirect('laundry:schedule')
    else:
        form = ReservationForm()

    return render(request, 'reserve.html', {'form': form})

def show_today(request):
    selected_date = None
    schedule = None

    if request.method == 'POST':
        form = DateForm(request.POST)
        if form.is_valid():
            selected_date = form.cleaned_data['date']
            # Pobierz rezerwacje dla wybranej daty
            schedule = get_schedule_for_date(selected_date)
    else:
        form = DateForm()
        selected_date = datetime.today().date()  # Domyślnie pokazuj dzisiejsze rezerwacje
        schedule = get_schedule_for_date(selected_date)

    return render(request, 'schedule.html', {'form': form, 'schedule': schedule, 'selected_date': selected_date})

# main/views.py
def show_selected_day(request):
    date_str = request.GET.get('date', '') # np http://localhost:8000/show_selected_day/?date=December%201%2C%202023
    
    # Przekształć datę ze stringa na obiekt datetime
    date = datetime.strptime(date_str, '%B %d, %Y')
    
    day_of_week = date.weekday()
    days = ["Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota", "Niedziela"]
    current_day = days[day_of_week]
    if request.method == 'POST':
        form = DateForm(request.POST)
        if form.is_valid():
            selected_date = form.cleaned_data['date']
            # Pobierz rezerwacje dla wybranej daty
            schedule = get_schedule_for_date(date)
    else:
        form = DateForm()
        selected_date = datetime.today().date()  # Domyślnie pokazuj dzisiejsze rezerwacje
        schedule = get_schedule_for_date(date)

    context = {'current_day': current_day,
               'form': form,
               'schedule': schedule,
               'selected_date': selected_date

               }
    return render(request, 'show_selected_day.html', context)

from .models import Reservation  # Importuj model rezerwacji

def get_reservations_for_date(selected_date):
    reservations = Reservation.objects.filter(date=selected_date)
    return reservations

from django.views import View
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect

@method_decorator(csrf_protect, name='dispatch')
class ShowSelectedDayView(View):
    template_name = 'show_selected_dayy.html'

    def get(self, request, *args, **kwargs):
        date_str = request.GET.get('date', '')
        
        # Przekształć datę ze stringa na obiekt datetime
        date = datetime.today().date()  # Domyślnie dzisiejsza data
        if date_str:
            try:
                date = datetime.strptime(date_str, '%B %d, %Y')
            except ValueError:
                # Dodaj obsługę błędu, na przykład przypisz dzisiejszą datę
                pass
        
        day_of_week = date.weekday()
        days = ["Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota", "Niedziela"]
        current_day = days[day_of_week]
        
        form = DateForm()
        schedule = get_schedule_for_date(date)
        reservation_form = ReservationForm()
        reservations = get_reservations_for_date(date)
        
        return render(request, self.template_name, {
            'form': form,
            'current_day': current_day,
            'schedule': schedule,
            'selected_date': date,
            'reservation_form': reservation_form,
            'reservations': reservations
        })

    def post(self, request, *args, **kwargs):
        form = DateForm(request.POST)
        if form.is_valid():
            selected_date = form.cleaned_data['date']
            schedule = get_schedule_for_date(selected_date)
            
            # Popraw: Przekazuj dane z żądania do formularza rezerwacji
            reservation_form = ReservationForm(request.POST)
            
            if reservation_form.is_valid():
                # Popraw: Zapisz rezerwację tylko jeśli formularz rezerwacji jest prawidłowy
                reservation = reservation_form.save(commit=False)
                reservation.user = request.user
                reservation.date = selected_date
                reservation.save()
                return redirect('laundry:show_selected_dayy')
                
            reservations = get_reservations_for_date(selected_date)
            return render(request, self.template_name, {
                'form': form,
                'current_day': selected_date.strftime('%A'),
                'schedule': schedule,
                'selected_date': selected_date,
                'reservation_form': reservation_form,
                'reservations': reservations
            })
        return render(request, self.template_name, {'form': form})

laundry/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Laundry Reservation</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
</head>


<body>
    <header>
        
       
        <body>
            <div class="container-fluid">
                <div class="row flex-nowrap">
                    <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                        <!-- Sidebar -->
                        {% include 'sidebar.html' %}
                    </div>
                    <div class="col">
                        <!-- Navbar -->
                        <div class="container">
                          
                            <div class="row">
                                <div class="col-8">
                                    <!-- Treść strony -->
                                </div>
                                <div class="col-4 ml-100">
                                    {% include 'navbar.html' %}
                                </div>
                            </div>
                        </div>
                        <!-- Treść strony -->
                        <div class="container">
                            <div class="row">
                                <div class="col-8">
                                    <!-- Treść strony -->
                                    {% block content %}{% endblock %}
                                </div>
                                <div class="col-4 ml-100">
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        
        
    </header>

    <main>
        
    </main>

    



    
</body>
</html>

laundry/templates/calendar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="reserveSlot.js" defer></script>
    <title>HTML Calendar</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 20px;
        }

        .calendar-container {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .calendar {
            width: 300px;
            margin: 0 auto;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
        }

        .calendar-header {
            background-color: #3498db;
            color: #fff;
            text-align: center;
            padding: 10px;
            font-size: 18px;
            border-top-left-radius: 5px;
            border-top-right-radius: 5px;
        }

        .calendar-body {
            padding: 10px;
        }

        .day {
            width: 40px;
            height: 40px;
            text-align: center;
            line-height: 40px;
            display: inline-block;
            margin: 5px;
            border-radius: 5px;
        }

        .day:hover {
            background-color: #3498db;
            color: #fff;
            cursor: pointer;
        }

        .hours-container {
            margin-top: 20px;
            display: flex;
            flex-wrap: wrap;
            gap: 5px;
        }

        .hour {
            width: 40px;
            height: 40px;
            text-align: center;
            line-height: 40px;
            background-color: #3498db;
            color: #fff;
            border-radius: 5px;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="calendar">
        <div class="calendar-header">
            <span id="prevMonth">&#9664;</span>
            <span id="currentMonth">December 2023</span>
            <span id="nextMonth">&#9654;</span>
        </div>
        <div class="calendar-body" id="calendarBody"></div>
    </div>

    <script>


        document.addEventListener('DOMContentLoaded', function() {
            const calendarBody = document.getElementById('calendarBody');
            const currentMonthElement = document.getElementById('currentMonth');
            const hoursContainer = document.createElement('div');
            hoursContainer.className = 'hours-container';
            document.body.appendChild(hoursContainer);

            function generateCalendar(year, month) {
                calendarBody.innerHTML = '';

                const daysInMonth = new Date(year, month + 1, 0).getDate();
                const firstDayOfMonth = new Date(year, month, 1).getDay();

                for (let i = 0; i < firstDayOfMonth; i++) {
                    const emptyDay = document.createElement('div');
                    emptyDay.className = 'day';
                    calendarBody.appendChild(emptyDay);
                }

                for (let day = 1; day <= daysInMonth; day++) {
                    const dayElement = document.createElement('div');
                    dayElement.className = 'day';
                    dayElement.textContent = day;
                    dayElement.addEventListener('click', function() {
                        handleDayClick(day, month, year);
                    });
                    calendarBody.appendChild(dayElement);
                }

                currentMonthElement.textContent = new Date(year, month, 1).toLocaleDateString('en-us', { month: 'long', year: 'numeric' });
            }

            function handleDayClick(day, month, year) {
                const selectedDate = new Date(year, month, day);
                const formattedDate = selectedDate.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

                // Przekieruj użytkownika na stronę z wybranym dniem
                window.location.href = `/show_selected_dayy/?date=${encodeURIComponent(formattedDate)}`;
            }

            let currentYear = new Date().getFullYear();
            let currentMonth = new Date().getMonth();

            generateCalendar(currentYear, currentMonth);

            document.getElementById('prevMonth').addEventListener('click', function() {
                currentMonth--;
                if (currentMonth < 0) {
                    currentMonth = 11;
                    currentYear--;
                }
                generateCalendar(currentYear, currentMonth);
            });

            document.getElementById('nextMonth').addEventListener('click', function() {
                currentMonth++;
                if (currentMonth > 11) {
                    currentMonth = 0;
                    currentYear++;
                }
                generateCalendar(currentYear, currentMonth);
            });

           

        });
    </script>

    
    </script>
</body>
</html>

laundry/templates/invalid_day.html
<!-- reservations/templates/reservations/invalid_day.html -->
<p>Nieprawidłowy dzień tygodnia. Proszę wybrać poniedziałek, wtorek, środę, czwartek, piątek, sobotę lub niedzielę.</p>

laundry/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Register</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="ms-auto">
            <a class="navbar-brand" href="#">Login</a>
        </div>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <a class="navbar-brand" href="#">Logout</a>
            </ul>
        </div>
    </div>
</nav>

laundry/templates/newcalendar.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calendar</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            margin: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .calendar-container {
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .calendar {
            width: 100%;
            max-width: 600px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 5px;
            margin-bottom: 20px;
        }

        .calendar-header {
            background-color: #3498db;
            color: #fff;
            text-align: center;
            padding: 10px;
            font-size: 18px;
            border-top-left-radius: 5px;
            border-top-right-radius: 5px;
        }

        .calendar-body {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
            padding: 10px;
        }

        .day {
            width: calc(100% / 7 - 10px);
            height: 30px;
            text-align: center;
            line-height: 30px;
            border-radius: 5px;
            box-sizing: border-box;
            margin: 5px 0;
        }

        .day:hover {
            background-color: #3498db;
            color: #fff;
            cursor: pointer;
        }

        .weekdays {
            display: flex;
            justify-content: space-around;
            margin-bottom: 5px;
            width: 100%;
        }

        .weekday {
            width: calc(100% / 7 - 10px);
            text-align: center;
            font-weight: bold;
            margin: 5px 0;
        }
    </style>
</head>

<body>
    <div class="calendar-container">
        <div class="calendar">
            <div class="calendar-header">
                <span id="prevMonth">&#9664;</span>
                <span id="currentMonth">{{ current_month_name }} {{ current_year }}</span>
                <span id="nextMonth">&#9654;</span>
            </div>
            <div class="weekdays">
                <div class="weekday">Sun</div>
                <div class="weekday">Mon</div>
                <div class="weekday">Tue</div>
                <div class="weekday">Wed</div>
                <div class="weekday">Thu</div>
                <div class="weekday">Fri</div>
                <div class="weekday">Sat</div>
            </div>
            <div class="calendar-body">
                {% for day_info in calendar_days %}
                    <div class="day day-{{ day_info.day_of_week }}">
                        {{ day_info.day }}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</body>

</html>

laundry/templates/reserve.html
{% extends "base.html" %}
{% block content %}

{% include 'calendar.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Laundry Reservation</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
</head>


    
  

    
    <br>
    <a href="{% url 'laundry:show_today' %}">Zobacz rezerwacje na dziś</a>

</html>



<style>
    /* Dodaj niestandardowe style dla formularza */
    form {
        max-width: 400px;
        margin: 0 auto;
    }

    /* Dodaj niestandardowe style dla przycisku rezerwacji */
    button {
        background-color: #4CAF50;
        color: white;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }
</style>


{% endblock %}

laundry/templates/schedule.html
{% if schedule %}
    <h2>Rezerwacje na {{ selected_date }}</h2>
    <table border="1">
        <thead>
            <tr>
                <th>Godzina</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for hour, status in schedule.items %}
                <tr>
                    <td>{{ hour }}</td>
                    <td>{{ status }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>Brak rezerwacji na wybraną datę.</p>
{% endif %}



<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Laundry Reservation</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
</head>
<h2>Rezerwacja prania</h2>
    <form method="post" action="{% url 'laundry:reserve_laundry' %}">
        {% csrf_token %}
        {{ form.media}}
        {{ form.as_p }}
       
    </form>

laundry/templates/show_selected_day.html
{% extends "base.html" %}
{% block content %}

<h2>Twoje rezerwacje na dzień {{ current_day}}</h2>
{% if schedule %}
    <table border="1">
        <thead>
            <tr>
                <th>Godzina</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for hour, status in schedule.items %}
                <tr>
                    <td>{{ hour }}</td>
                    <td>{{ status }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>Brak rezerwacji na wybraną datę.</p>
{% endif %}

{{ form.media}}

<body>
    <h2>Rezerwacja prania</h2>
    <form method="post" action="{% url 'laundry:reserve_laundry' %}">
        {% csrf_token %}
        {{ form.media}}
        {{ form.as_p }}
       
        <button type="submit">Dokonaj rezerwacji</button>
    </form>
</body>   

{% endblock %}

laundry/templates/show_selected_dayy.html
{% extends "base.html" %}
{% block content %}



<h2>Twoje rezerwacje na dzień {{ current_day}}</h2>
{% if schedule %}
    <table border="1">
        <thead>
            <tr>
                <th>Godzina</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for hour, status in schedule.items %}
                <tr>
                    <td>{{ hour }}</td>
                    <td>{{ status }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>Brak rezerwacji na wybraną datę.</p>
{% endif %}





<!-- Formularz do nowej rezerwacji -->
<form method="post" action="{% url 'laundry:show_selected_dayy' %}">
    {% csrf_token %}
    {{ form.media }}
    {{ reservation_form.as_p }}
    <input type="submit" value="Zarezerwuj">
</form>

{% endblock %}

laundry/templates/sidebar.html
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fs-5 d-none d-sm-inline">Menu</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item">
                        <a href="#" class="nav-link align-middle px-0">
                            <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                        </a>
                    </li>
                    <li>
                        <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Dashboard</span> </a>
                        <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1 </a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2 </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Orders</span></a>
                    </li>
                    <li>
                        <a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
                            <i class="fs-4 bi-bootstrap"></i> <span class="ms-1 d-none d-sm-inline">Bootstrap</span></a>
                        <ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#submenu3" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Products</span> </a>
                            <ul class="collapse nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 1</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 2</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 3</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 4</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Customers</span> </a>
                    </li>
                </ul>
                <hr>
                <div class="dropdown pb-4">
                    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="https://github.com/mdo.png" alt="hugenerd" width="30" height="30" class="rounded-circle">
                        <span class="d-none d-sm-inline mx-1">loser</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                        <li><a class="dropdown-item" href="#">New project...</a></li>
                        <li><a class="dropdown-item" href="#">Settings</a></li>
                        <li><a class="dropdown-item" href="#">Profile</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Sign out</a></li>
                    </ul>
                </div>
            </div>
        </div>
        
        <div class="container">
          <div class="row">
              <div class="col-8">
                  <!-- Treść strony -->
              </div>
              <div class="col-4 ml-100">
                  {% comment %} {% include 'navbar.html' %} {% endcomment %}
              </div>
          </div>
      </div>
      
    </div>
  </div>